import type { SubscriptionPlan } from '@/types/subscription';

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'starter',
    name: 'Başlangıç',
    description: 'Küçük işletmeler için temel özellikler',
    pricing: {
      monthly: 1000,
      quarterly: 2700, // %10 indirim
      'semi-annual': 5100, // %15 indirim
      annual: 9600, // %20 indirim
    },
    discounts: {
      monthly: 0,
      quarterly: 10,
      'semi-annual': 15,
      annual: 20,
    },
    features: {
      maxStaff: 3,
      maxServices: 20,
      maxMonthlyBookings: 200,
      customerManagement: true,
      customerNotes: false,
      customerTags: false,
      loyaltyProgram: false,
      basicAnalytics: true,
      advancedAnalytics: false,
      customReports: false,
      exportData: false,
      smsNotifications: false,
      emailNotifications: true,
      whatsappIntegration: false,
      queueManagement: true,
      reviewManagement: true,
      reviewResponses: false,
      onlinePayments: false,
      depositPayments: false,
      customBranding: false,
      customDomain: false,
      supportLevel: 'email',
      multiLocation: false,
      apiAccess: false,
      whiteLabel: false,
    },
  },
  {
    id: 'professional',
    name: 'Profesyonel',
    description: 'Büyüyen işletmeler için gelişmiş özellikler',
    pricing: {
      monthly: 2500,
      quarterly: 6750, // %10 indirim
      'semi-annual': 12750, // %15 indirim
      annual: 24000, // %20 indirim
    },
    discounts: {
      monthly: 0,
      quarterly: 10,
      'semi-annual': 15,
      annual: 20,
    },
    popular: true,
    features: {
      maxStaff: 10,
      maxServices: 50,
      maxMonthlyBookings: 500,
      customerManagement: true,
      customerNotes: true,
      customerTags: true,
      loyaltyProgram: true,
      basicAnalytics: true,
      advancedAnalytics: true,
      customReports: false,
      exportData: true,
      smsNotifications: true,
      emailNotifications: true,
      whatsappIntegration: true,
      queueManagement: true,
      reviewManagement: true,
      reviewResponses: true,
      onlinePayments: true,
      depositPayments: true,
      customBranding: false,
      customDomain: false,
      supportLevel: 'priority',
      multiLocation: false,
      apiAccess: false,
      whiteLabel: false,
    },
  },
  {
    id: 'business',
    name: 'İşletme',
    description: 'Kurumsal işletmeler için tam özellikler',
    pricing: {
      monthly: 5000,
      quarterly: 13500, // %10 indirim
      'semi-annual': 25500, // %15 indirim
      annual: 48000, // %20 indirim
    },
    discounts: {
      monthly: 0,
      quarterly: 10,
      'semi-annual': 15,
      annual: 20,
    },
    features: {
      maxStaff: 25,
      maxServices: 'unlimited',
      maxMonthlyBookings: 'unlimited',
      customerManagement: true,
      customerNotes: true,
      customerTags: true,
      loyaltyProgram: true,
      basicAnalytics: true,
      advancedAnalytics: true,
      customReports: true,
      exportData: true,
      smsNotifications: true,
      emailNotifications: true,
      whatsappIntegration: true,
      queueManagement: true,
      reviewManagement: true,
      reviewResponses: true,
      onlinePayments: true,
      depositPayments: true,
      customBranding: true,
      customDomain: false,
      supportLevel: 'priority',
      multiLocation: true,
      apiAccess: true,
      whiteLabel: false,
    },
  },
  {
    id: 'enterprise',
    name: 'Kurumsal',
    description: 'Büyük organizasyonlar için sınırsız özellikler',
    pricing: {
      monthly: 10000,
      quarterly: 27000, // %10 indirim
      'semi-annual': 51000, // %15 indirim
      annual: 96000, // %20 indirim
    },
    discounts: {
      monthly: 0,
      quarterly: 10,
      'semi-annual': 15,
      annual: 20,
    },
    features: {
      maxStaff: 'unlimited',
      maxServices: 'unlimited',
      maxMonthlyBookings: 'unlimited',
      customerManagement: true,
      customerNotes: true,
      customerTags: true,
      loyaltyProgram: true,
      basicAnalytics: true,
      advancedAnalytics: true,
      customReports: true,
      exportData: true,
      smsNotifications: true,
      emailNotifications: true,
      whatsappIntegration: true,
      queueManagement: true,
      reviewManagement: true,
      reviewResponses: true,
      onlinePayments: true,
      depositPayments: true,
      customBranding: true,
      customDomain: true,
      supportLevel: 'dedicated',
      multiLocation: true,
      apiAccess: true,
      whiteLabel: true,
    },
  },
  {
    id: 'custom',
    name: 'Özel Çözüm',
    description: 'İhtiyaçlarınıza özel tasarlanmış paket',
    pricing: {
      monthly: 0,
      quarterly: 0,
      'semi-annual': 0,
      annual: 0,
    },
    discounts: {
      monthly: 0,
      quarterly: 0,
      'semi-annual': 0,
      annual: 0,
    },
    customPricing: true,
    features: {
      maxStaff: 'unlimited',
      maxServices: 'unlimited',
      maxMonthlyBookings: 'unlimited',
      customerManagement: true,
      customerNotes: true,
      customerTags: true,
      loyaltyProgram: true,
      basicAnalytics: true,
      advancedAnalytics: true,
      customReports: true,
      exportData: true,
      smsNotifications: true,
      emailNotifications: true,
      whatsappIntegration: true,
      queueManagement: true,
      reviewManagement: true,
      reviewResponses: true,
      onlinePayments: true,
      depositPayments: true,
      customBranding: true,
      customDomain: true,
      supportLevel: 'dedicated',
      multiLocation: true,
      apiAccess: true,
      whiteLabel: true,
    },
  },
];

// Trial süresi (gün)
export const TRIAL_PERIOD_DAYS = 7;

// Özellik açıklamaları
export const FEATURE_DESCRIPTIONS: Record<string, string> = {
  maxStaff: 'Ekleyebileceğiniz personel sayısı',
  maxServices: 'Tanımlayabileceğiniz hizmet sayısı',
  maxMonthlyBookings: 'Aylık randevu/rezervasyon limiti',
  customerManagement: 'Müşteri listesi ve temel bilgiler',
  customerNotes: 'Müşteri notları ve geçmiş',
  customerTags: 'Müşteri etiketleme ve segmentasyon',
  loyaltyProgram: 'Sadakat programı ve puan sistemi',
  basicAnalytics: 'Temel istatistikler ve raporlar',
  advancedAnalytics: 'Detaylı analitik ve tahminler',
  customReports: 'Özel rapor oluşturma',
  exportData: 'Veri dışa aktarma (Excel, PDF)',
  smsNotifications: 'SMS bildirimleri',
  emailNotifications: 'E-posta bildirimleri',
  whatsappIntegration: 'WhatsApp entegrasyonu',
  queueManagement: 'Sıra yönetim sistemi',
  reviewManagement: 'Yorum ve değerlendirme yönetimi',
  reviewResponses: 'Yorumlara yanıt verme',
  onlinePayments: 'Online ödeme alma',
  depositPayments: 'Kapora/depozito sistemi',
  customBranding: 'Özel marka görünümü',
  customDomain: 'Özel alan adı',
  supportLevel: 'Destek seviyesi',
  multiLocation: 'Çoklu şube yönetimi',
  apiAccess: 'API erişimi',
  whiteLabel: 'Beyaz etiket çözümü',
};
